# Generated by Django 4.2.23 on 2025-08-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Update',
                'verbose_name_plural': 'News Updates',
                'db_table': 'news_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='University Module Registration', max_length=100)),
                ('site_description', models.TextField(default='A comprehensive module registration system for university students')),
                ('contact_email', models.EmailField(default='info@university.edu', max_length=254)),
                ('contact_phone', models.CharField(default='+1-234-567-8900', max_length=20)),
                ('address', models.TextField(default='123 University Ave, City, State 12345')),
                ('about_content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_registration_open', models.BooleanField(default=True, help_text='Is module registration currently open?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
                'db_table': 'site_configuration',
            },
        ),
    ]
